// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoGameExchangeHypermediaAPI.Data;

#nullable disable

namespace VideoGameExchangeHypermediaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130221148_AddTradeOffers")]
    partial class AddTradeOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoGameExchangeHypermediaAPI.Models.TradeModels.TradeOffer", b =>
                {
                    b.Property<int>("TradeOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trade_offer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeOfferId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int")
                        .HasColumnName("from_user_id");

                    b.Property<int>("OfferedGameId")
                        .HasColumnType("int")
                        .HasColumnName("offered_game_id");

                    b.Property<int>("RequestedGameId")
                        .HasColumnType("int")
                        .HasColumnName("requested_game_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int")
                        .HasColumnName("to_user_id");

                    b.HasKey("TradeOfferId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("OfferedGameId");

                    b.HasIndex("RequestedGameId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Trade_Offers");
                });

            modelBuilder.Entity("VideoGameExchangeHypermediaAPI.Models.UserModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("street_address");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VideoGameExchangeHypermediaAPI.Models.VideoGameModels.VideoGame", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("condition");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("PreviousOwnersCount")
                        .HasColumnType("int")
                        .HasColumnName("previous_owners_count");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("publisher");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("system");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int")
                        .HasColumnName("year_published");

                    b.HasKey("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Video_Games");
                });

            modelBuilder.Entity("VideoGameExchangeHypermediaAPI.Models.TradeModels.TradeOffer", b =>
                {
                    b.HasOne("VideoGameExchangeHypermediaAPI.Models.UserModels.User", "FromUser")
                        .WithMany("SentOffers")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoGameExchangeHypermediaAPI.Models.VideoGameModels.VideoGame", "OfferedGame")
                        .WithMany("OfferedInOffers")
                        .HasForeignKey("OfferedGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoGameExchangeHypermediaAPI.Models.VideoGameModels.VideoGame", "RequestedGame")
                        .WithMany("RequestedInOffers")
                        .HasForeignKey("RequestedGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoGameExchangeHypermediaAPI.Models.UserModels.User", "ToUser")
                        .WithMany("ReceivedOffers")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("OfferedGame");

                    b.Navigation("RequestedGame");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("VideoGameExchangeHypermediaAPI.Models.VideoGameModels.VideoGame", b =>
                {
                    b.HasOne("VideoGameExchangeHypermediaAPI.Models.UserModels.User", "User")
                        .WithMany("VideoGames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VideoGameExchangeHypermediaAPI.Models.UserModels.User", b =>
                {
                    b.Navigation("ReceivedOffers");

                    b.Navigation("SentOffers");

                    b.Navigation("VideoGames");
                });

            modelBuilder.Entity("VideoGameExchangeHypermediaAPI.Models.VideoGameModels.VideoGame", b =>
                {
                    b.Navigation("OfferedInOffers");

                    b.Navigation("RequestedInOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
